### ISSUE TITLE
provide guidelines for using action creators in docs

### ISSUE THREAD

**Issue by wafflepie** [lundegaard/redux-tools#138]
After consultations with @tommmyy the best practices to follow are:

Only use `makeConstantActionCreator`, `makeSimpleActionCreator`, `makeBinaryActionCreator` in your applications. Do not use any other action creator factories in your application code. `makeActionCreator` is meant to only be used as a "factory for other factories" (i.e. `makeActionCreator` is used to create the aforementioned action creator factories).

The reason is that logic should be left to the reducer. Action creator usage should be transparent: whatever you pass to them ends up in the payload/meta. Use `constant`/`simple`/`binary` to determine how many arguments are expected by the action creator. This enables you to "stop thinking" when using action creators (there's no actual logic involved in using them).

https://redux.js.org/style-guide/style-guide#put-as-much-logic-as-possible-in-reducers

Depends on #73 #108

**Comment by tommmyy** [comment]
@wafflepie totally agreed
