### ISSUE TITLE
Add note to README about bug in redux-devtools-extension

### ISSUE THREAD

**Issue by tommmyy** [lundegaard/redux-tools#34]
After injecting either a reducer or a middleware `redux-devtools-extension` stops the logging of actions.
Fix is to set options to devtools like that:

```
	const composeEnhancers = composeWithDevTools({
		// NOTE: if not set the extension breaks after injecting reducers
		latency: 0,
		// NOTE: if `true` extension breaks after injecting reducers
		shouldHotReload: false,
	});

```

I think it would be useful to warn our precious users about that.

**Comment by wafflepie** [comment]
Closed by #48
