### ISSUE TITLE
Improve utility functions arsenal

### ISSUE THREAD

**Issue by wafflepie** [lundegaard/redux-tools#73]
- [x] Add support for variadic action creators (`makeBinaryActionCreator`)
- [x] Add `makeMiddleware` and `composeMiddleware` to `middleware` (`makeMiddleware` will not be added because it is too specific, perhaps in another issue)
- [x] Add `scopeReducer` to `reducers` (not added, but no longer necessary due to #155)
- [ ] Add `useNamespacedSelector` (optional feature arg) to `@redux-tools/namespaces-react`

**Comment by wafflepie** [comment]
Fix makeSimpleActionCreator so that it accepts zero arguments as well

**Comment by wafflepie** [comment]
Add makeMiddleware

**Comment by tommmyy** [comment]
👍 love it

**Comment by tommmyy** [comment]
please add `useFeaturedSelector` and `useNamespacedSelector` too

**Comment by wafflepie** [comment]
Regarding `useFeaturedSelector`, `useNamespacedSelector` and `useNamespacedDispatch`, I'll still have to think more about their signatures.

They should a) accept features and b) accept a forced namespace. Currently, `getStateByNamespace` and `getStateByAction` are in a weird state and should be looked at (e.g. `getStateByAction` expects `action.meta.feature` which is no longer present in our code).

**Comment by tommmyy** [comment]
@wafflepie they should be also valid accoriding to react-hooks eslint plugin.
