### ISSUE TITLE
How to set initial state for dynamically added reducer?

### ISSUE THREAD

**Issue by jsifalda** [lundegaard/redux-tools#79]
Hey, it seems that with usage of withReducers(), the initial state passed during store initialization is ignored. 

Typical use case is for reason of local storage to set reducer state:
![CleanShot 2019-10-21 at 3 21 24 PM@2x](https://user-images.githubusercontent.com/1549390/67208816-82a7be80-f416-11e9-8882-72754a3a8a9c.jpg)

Instead, I should be doing something like this:

![CleanShot 2019-10-21 at 3 22 16 PM@2x](https://user-images.githubusercontent.com/1549390/67208852-93f0cb00-f416-11e9-90db-ee46b53d72e4.jpg)

Ideally, there could be api to provide initial state together withReducers() HOC? 

Thanks in advance.

**Comment by wafflepie** [comment]
Hey there, the intended usage is the first method you described, which should be working fine (we are using this throughout our internal projects). To make the second method work as well, it is necessary to swap out the `combineReducers` implementation for a custom one, see #76.

Could you clarify why you'd need to use the second method instead of the first one?

**Comment by jsifalda** [comment]
> Hey there, the intended usage is the first method you described, which should be working fine (we are using this throughout our internal projects). To make the second method work as well, it is necessary to swap out the `combineReducers` implementation for a custom one, see #76.
> 
> Could you clarify why you'd need to use the second method instead of the first one?

Can you clarify how to use swap out implementation of combineReducers for this case? 

And to clarify why the second usage is wrong... mainly it is because it creates side effects and external dependency which is not testable (without mocks). Dont forget the reducers should be pure functions without any dependencies which is not the case if you use localStorage for initial state in reducer

**Comment by wafflepie** [comment]
Modification of redux-tools is necessary, see `packages/reducers/src/combineReducerEntries.js`.

I think that in the second method you're just replacing a problem with another one (testability and impure reducers compared to features being responsible for their own data). To have it "correct", you'd need to pass the token to the `createStore` function, but why should the entire store know about the data source for a dependent reducer?

Another option is to instead have an authentication reducer factory and pass the `localStorage` data externally, to avoid mocking (i.e. the reducer factory would accept initial data when injecting).

That being said, redux-tools should not limit you in the way you solve this issue, so #76 should be fixed regardless (still a bug).

**Comment by wafflepie** [comment]
We use the first method because the side-effect is performed only during initialization, which is IMO fine for reducers (It doesn't cause any issues, it just isn't "clean" according to the documentation and FP principles.).

**Comment by wafflepie** [comment]
fixed by #86
