### ISSUE TITLE
Redux store should remove reducer's data after ejecting 

### ISSUE THREAD

**Issue by jsifalda** [lundegaard/redux-tools#80]
![CleanShot 2019-10-29 at 3 35 27 PM@2x](https://user-images.githubusercontent.com/1549390/67777326-dd1dcc00-fa61-11e9-940d-e4e62b1fc658.jpg)

Is this an expected behavior? I would expect that after ejecting reducer (in other words, once the component which contains withReducers() is unmounted), reducer data from store should be removed, right? And if not so, there should be at least option to do so. 
Because otherwise, if there is an middleware which adds items on fired action, it will created duplicated data. 

Thanks in advance.

**Comment by wafflepie** [comment]
fixed by #86
