### ISSUE TITLE
makeEnhancer from @redux-tools/middleware invalidate action returns - it always returns undefined

### ISSUE THREAD

**Issue by jsifalda** [lundegaard/redux-tools#82]
If I have a middleware which turns my dispatched actions into promises, I want to be able to get that promise back dispatching action eg.:
`const promise = dispatch(action())`
but because of makeEnhancer from @redux-tools/middleware, it always returns undefined instead of promise.

**Comment by wafflepie** [comment]
Sorry about that! Will take a look next week.
